package com.example.redbus.models

class UserItemModel() {
    val arrival_time = ""
    val booking_amount_paid = ""
    val booking_user_email = ""
    val booking_user_phone = ""
    val bus_company = ""
    val bus_name = ""
    val departure_time = ""
    val destination_location = ""
    val source_location = ""
    val travel_date = ""
    val user_age1 = ""
    val user_gender1 = ""
    val user_name1 = ""
    val seatid1 = ""
    val user_age2 = ""
    val user_gender2 = ""
    val user_name2 = ""
    val seatid2 = ""
    val user_age3 = ""
    val user_gender3 = ""
    val user_name3 = ""
    val seatid3 = ""
    val user_age4 = ""
    val user_gender4 = ""
    val user_name4 = ""
    val seatid4 = ""
    val user_age5 = ""
    val user_gender5 = ""
    val user_name5 = ""
    val seatid5 = ""
    val user_age6 = ""
    val user_gender6 = ""
    val user_name6 = ""
    val seatid6 = ""
}